BaseVersion/Areas/Customers/Models/Register.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace BaseVersion.Areas.Customers.Models
{
    public class Register
    {
        [Required]
        public string Name { get; set; }

        [EmailAddress]
        public string Email { get; set; }

        [StringLength(15, MinimumLength = 5)]
        [RegularExpression(@"[0-9]+$")]
        [Required]
        public string Phone { get; set; }
        [Required]
        public string Password { get; set; }
    }
}

BaseVersion/Areas/Customers/Controllers/CustomerController.cs
using BaseVersion.Controllers;
using BaseVersion.Helpers;
using BaseVersion.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace BaseVersion.Areas.Customers.Controllers
{
    [CustomAuthorize(Roles = CustomHelper.SUPERADMIN + "," + CustomHelper.ADMINISTRATOR)]
    public class CustomerController : BaseController
    {
        private BaseVersionEntities db = new BaseVersionEntities();

        // GET: Customers/Customer
        public ActionResult Index()
        {
            return View();
        }

        [HttpGet]
        public ActionResult GetAjaxData()
        {
            #region Build Order by Clause And Pagination parameters
            Pagination pagination = new Pagination();
            pagination = this.DataTablePagination(pagination);
            #endregion

            int? count = 0;
            string name = null;
            string phone = null;
            string email = null;
            name = CommonHelper.PrepareFilterString(Request["sSearch_0"]);
            phone = CommonHelper.PrepareFilterString(Request["sSearch_1"]);
            email = CommonHelper.PrepareFilterString(Request["sSearch_2"]);

            List<spCustomerGetByPage_Result> customers = db.spCustomerGetByPage(name, email, phone, pagination.SortColIndex, pagination.OrderByColumnDir, pagination.PageNum, pagination.DisplayLength).ToList();

            if (customers.Count > 0)
            {
                count = customers.First().TotalRows;
            }
            var Data = customers.Select(d => new string[] {
                            d.Name,
                            d.PhoneNumber,
                            d.Email,
                            d.Id.ToString()}).ToArray();
            return Json(new
            {
                aaData = Data,
                iTotalDisplayRecords = count,
                iTotalRecords = count,
                sEcho = Request.Params["sEcho"]
            }, JsonRequestBehavior.AllowGet);
        }

    }
}

BaseVersion/Areas/Customers/Views/Customer/Index.cshtml
@using BaseVersion.Resources
@using BaseVersion.Areas.Customers.Resources

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@section breadcrumb{
    <div class="page-breadcrumbs">
        <ul class="breadcrumb">
            <li class="active">
                <i class="fa fa-users"></i>
                @CustomerResource.Customers
            </li>
        </ul>
    </div>
}
<!-- Page Body -->
<div class="page-body">
    <div class="row">
        <div class="col-lg-12 col-sm-12 col-xs-12">
            <div class="widget">
                <div class="widget-header bordered-bottom bordered-blue">
                    <span class="widget-caption">@Resource.BtnSearch</span>
                    <div class="widget-buttons">
                        <a href="javascript:;" data-toggle="maximize">
                            <i class="fa fa-expand"></i>
                        </a>
                        <a href="javascript:;" data-toggle="collapse">
                            <i class="fa fa-minus"></i>
                        </a>
                    </div>
                </div>
                <div class="widget-body">
                    <div id="horizontal-form">
                        <form class="form-horizontal form-search" role="form">
                            <div class="row">
                                <div class="col-md-6">
                                    <input type="text" id="name" placeholder="@Resource.Name" class="form-control">
                                    <div class="horizontal-space"></div>
                                </div>
                                <div class="col-md-6">
                                    <input type="text" id="phone" placeholder="@Resource.Phone" class="form-control">
                                    <div class="horizontal-space"></div>
                                </div>
                                <div class="col-md-6">
                                    <input type="text" id="email" placeholder="@Resource.Email" class="form-control">
                                    <div class="horizontal-space"></div>
                                </div>
                            </div>
                            <div>
                                <a href="javascript:;" class="btn btn-sm btn-default btn-info" onclick="filterTable('#customer_datatable')">@Resource.BtnSearch</a>
                                <a href="javascript:;" class="btn btn-sm btn-default btn-danger" onclick="clearfilterTable('#customer_datatable')">@Resource.BtnCancelSearch</a>
                            </div>
                        </form>
                    </div>
                </div>

            </div>
        </div>
    </div>

    <div class="row">
        <div class="col-xs-12 col-md-12">
            <div class="widget">
                <div class="widget-header bordered-bottom bordered-blue">
                    <span class="widget-caption">@CustomerResource.CustomerList</span>
                    <div class="widget-buttons">
                        @*<a href="javascript:;" id="print" data-toggle="tooltip" data-placement="bottom" data-original-title="@Resource.Print">
                                <i class="fa fa-print"></i>
                            </a>*@
                        <a href="javascript:;" id="export_excel" data-toggle="tooltip" data-placement="bottom" data-original-title="@Resource.DownloadExcel">
                            <i class="fa fa-download"></i>
                        </a>
                        <a href="javascript:;" data-toggle="maximize">
                            <i class="fa fa-expand"></i>
                        </a>
                        <a href="javascript:;" data-toggle="collapse">
                            <i class="fa fa-minus"></i>
                        </a>
                    </div>
                </div>
                <div class="widget-body">
                    <table id="customer_datatable" class="table table-striped table-bordered table-hover dt-responsive">
                        <thead>
                            <tr>
                                <th style="width:35%">@Resource.Name</th>
                                <th style="width:20%"> @Resource.Phone </th>
                                <th style="width:25%"> @Resource.Email </th>
                                <th style="width:10%"> @Resource.Operation</th>
                            </tr>
                        </thead>
                        <tbody></tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>

<!-- /Page Body -->
@section scripts{
    <script src="@Url.Content("~/Areas/Customers/App/index.js")"></script>

    <script>

        var datatable_parameters = {
            TableName: '#customer_datatable',
            ActionUrl: '@Url.Action("GetAjaxData", "Customer", new { area = "Customers" })',
            DetailsUrl: '@Url.Action("Details", "Customer", new { area = "Customers" })',
            Edit: '@Resource.BtnEdit',
            Delete: '@Resource.BtnDelete',
            Details: '@Resource.BtnDetails',
            Activate: '@Resource.Activate',
            Deactivate: '@Resource.Activate',
            NumberRows: '@Resource.NumberRows',
            NoData : '@Resource.NoData',
            Display: '@Resource.Display',
            To : '@Resource.To',
            From: '@Resource.From',
            Rows: '@Resource.Rows',
            Currency: '@Resource.SAR'
        }

        insialise_customer_datatable(datatable_parameters);

        function delete_model(deleteButtonPressed, id) {
            custom_delete_action(deleteButtonPressed, tableName, id, null, '@Url.Action("DeleteConfirmed", "Customer")', "@Resource.ConfirmDelete", "@Resource.Yes", "@Resource.No");
        }

        $("#export_excel").on('click', function () {
            window.location.href = '@Url.Action("ExportData", "Customer", new { area = "Customers" })';
        });

    </script>
}